/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adamasmaca;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahmut
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    String kelimeler = "C:\\P2Oyun\\TXTDosyalar\\Kelimeler.txt";
    String oyunlar = "C:\\P2Oyun\\TXTDosyalar\\oyunlar.txt";
    String pictures = "C:\\P2Oyun\\Resimler";
    String log = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
    
    File logData = new File(log);
    File wordsData = new File(kelimeler);
    File gameData = new File(oyunlar);
    String hedefKelime;
    
    int gecenSaniye = 0;
    Timer kronometre;
    int score = 0;
    boolean dogruTahmin;
    int acikHarfSayisi = 0;
    int yanlisTahmin;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        eskiSkorlar();
        logGoster();
        
        kronometre = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                gecenSaniye++;
                
                jLabel3.setText(gecenSaniye + " Saniye");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        resimEtiketi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Harf Tahmini:");

        jLabel2.setText("Kelime Tahmini:");

        jButton1.setText("Tahmin Et");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resimEtiketi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(resimEtiketi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        jLabel3.getAccessibleContext().setAccessibleName("jLable3");

        jTabbedPane1.addTab("Oyun Oyna", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Puan", "Zaman", "Sonuç", "Tarih", "Saat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Verileri sil");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eski Skorları Görüntüle", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Durum Mesajı", "Tarih", "Saat"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Verileri sil");
        jButton3.setMaximumSize(new java.awt.Dimension(82, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(82, 23));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Logları Görüntüle", jPanel3);

        jMenu1.setText("Menü");

        jMenuItem1.setText("Oyunu Başlat");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Oyunu Yeniden Başlat");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String harf = jTextField2.getText().toUpperCase();
        String kelime = jTextField1.getText().toUpperCase();
        
        if(!harf.isEmpty()){
            dogruTahmin = false;
            char girilenHarf = harf.charAt(0);
            
            
            for(int i = 0; i < hedefKelime.length(); i++){
                
                if(hedefKelime.charAt(i) == girilenHarf){
                    JLabel ilgiliEtiket = (JLabel) jPanel4.getComponent(i);
                    
                    ilgiliEtiket.setText(String.valueOf(girilenHarf));
                    
                    dogruTahmin = true;
                    score += 5;
                    
                }
                
                
            }
            if(dogruTahmin){
                
                jTextField2.setText("");
                //kazanma durumunu kontrol et.(tüm yıldızlar açıldı mı?)
                for(int j = 0; j < hedefKelime.length(); j++ ){
                    JLabel etiket = (JLabel) jPanel4.getComponent(j);
                    if(!etiket.getText().equals("*")){
                        
                        acikHarfSayisi++;
                    }
                }
                if(hedefKelime.length() ==acikHarfSayisi){
                    //kazanma durumunda yapılanlar.
                    kronometre.stop();
                    sonucYaz(score, gecenSaniye, "Kazanıldı");
                    JOptionPane.showMessageDialog(this,"Kazandınız!");
                    eskiSkorlar();
                }else{
                    acikHarfSayisi = 0;
                }
                
            }else{
                jTextField2.setText("");
                //Yanlış harf sayısını arttır ve resmi güncelle.
                yanlisTahmin++;
                score-=3;
                
                if(yanlisTahmin == 11){
                    //Oyunu bitir. Kronometreyi durdur. Oyunlar.txt'ye kaydetme işlemlerini yap.
                    resmiGuncelle(yanlisTahmin);
                    kronometre.stop();
                    sonucYaz(score, gecenSaniye, "Yenilgi");
                    JOptionPane.showMessageDialog(this, "Oyunu kaybettiniz! Kelime: " + hedefKelime);
                    eskiSkorlar();
                }else{
                    resmiGuncelle(yanlisTahmin);
                }
                
            }
            
            
        }else if(!kelime.isEmpty()){
            dogruTahmin = false;
            char[] girilenKelime = kelime.toCharArray();
            
            
            if(kelime.equals(hedefKelime)){
                dogruTahmin = true;
                 
                for(int i = 0; i < hedefKelime.length(); i++){
                
                    
                        JLabel ilgiliEtiket = (JLabel) jPanel4.getComponent(i);

                        ilgiliEtiket.setText(String.valueOf(girilenKelime[i]));

                        dogruTahmin = true;
                        score += 5;
                    
               
                
                }
                      

                        
                jTextField1.setText("");
                //Kazandığı zaman yapılacaklar.
                kronometre.stop();
                sonucYaz(score, gecenSaniye, "Kazanıldı");
                JOptionPane.showMessageDialog(this,"Kazandınız!");
                eskiSkorlar();
            }else{
                //yanlış tahmin yaptığı için fotoğraf değişecek.
                score-=3;
                yanlisTahmin++;
                jTextField1.setText("");
                
                if(yanlisTahmin == 11){
                    //Oyunu bitir. Kronometreyi durdur. Oyunlar.txt'ye kaydetme işlemlerini yap.
                    resmiGuncelle(yanlisTahmin);
                    kronometre.stop();
                    sonucYaz(score, gecenSaniye, "Yenilgi");
                    JOptionPane.showMessageDialog(this, "Oyunu kaybettiniz! Kelime: " + hedefKelime);
                    eskiSkorlar();
                }else{
                    resmiGuncelle(yanlisTahmin);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this,"Lütfen bir harf veya kelime giriniz!");
        }
        jLabel4.setText("Puan: " + score);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        gecenSaniye = 0;
        jLabel3.setText("0 Saniye");
        kronometre.start();
        
        acikHarfSayisi = 0;
        yanlisTahmin = 0;
        score = 0;
        hedefKelime = randomWordsChoose();
        
        jPanel4.removeAll();
        for(int i = 0; i < hedefKelime.length(); i++){
            
            JLabel harfEtiketi = new JLabel("*");
            
            harfEtiketi.setFont(new Font("Tahoma", 1, 24));
            
            jPanel4.add(harfEtiketi);
            
        }
        
        jPanel4.revalidate();
        jPanel4.repaint();
        
        jLabel4.setText("Puan: " + score);
        
        //dosyadan çektiğimiz fotoğrafları layout'dan resetle.
        resimEtiketi.setIcon(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        gecenSaniye = 0;
        jLabel3.setText("0 Saniye");
        kronometre.start();
        
        acikHarfSayisi = 0;
        yanlisTahmin = 0;
        score = 0;
        hedefKelime = randomWordsChoose();
        
        jPanel4.removeAll();
        for(int i = 0; i < hedefKelime.length(); i++){
            
            JLabel harfEtiketi = new JLabel("*");
            
            harfEtiketi.setFont(new Font("Tahoma", 1, 24));
            
            jPanel4.add(harfEtiketi);
            
        }
        
        jPanel4.revalidate();
        jPanel4.repaint();
        
        jLabel4.setText("Score: " + score);
        
        //dosyadan çektiğimiz fotoğrafları layout'dan resetle.
        resimEtiketi.setIcon(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //şifre sorulacak, şfre kontrol edilecek. Eğer şifre doğruysa oyunlar.txt temizlenecek. Şifre yanlışsa log kısmına yazılacak.
        passwordCheck sifreEkrani = new passwordCheck();
        
        sifreEkrani.setVisible(true);
        
        
        
        if(sifreEkrani.isSifreDogru()){
            try{
                FileWriter writer = new FileWriter(gameData);
                
                writer.write("");
                writer.close();
                
                eskiSkorlar();
                
                JOptionPane.showMessageDialog(this, "Oyun verileri başarıyla silindi");
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Oyun verileri silinirken bir sorun oluştu!");
            }
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        passwordCheck sifreEkrani = new passwordCheck();
        
        sifreEkrani.setVisible(true);
        
        
        
        if(sifreEkrani.isSifreDogru()){
            try{
                FileWriter writer = new FileWriter(logData);
                
                writer.write("");
                writer.close();
                
                logGoster();
                
                JOptionPane.showMessageDialog(this, "Log verileri başarıyla silindi");
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Log verileri silinirken bir sorun oluştu!");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private String randomWordsChoose(){
        ArrayList<String> kelimeListesi = new ArrayList<>();
        String secilenKelime= "";
        
        try{
            BufferedReader reader = new BufferedReader(new FileReader(wordsData));
            String satir;
            
            while((satir = reader.readLine()) != null){
                
                if(!satir.trim().isEmpty()){
                    kelimeListesi.add(satir.trim().toUpperCase());
                }
            }
            reader.close();
            
            if(kelimeListesi.size() > 0){
                Random rnd = new Random();
                
                int rndIndex = rnd.nextInt(kelimeListesi.size());
                
                secilenKelime = kelimeListesi.get(rndIndex);
                
            }else{
                JOptionPane.showMessageDialog(this,"kelimeler.txt dosyası boş!", "Hata", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this,"kelimeler okunurken bir hata oldu!" + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
        
        
        return secilenKelime;
    }
    
    private void resmiGuncelle(int hataSayisi){
        
        String resimYolu = pictures + "\\" + hataSayisi + ".jpg";
        
        ImageIcon ikon = new ImageIcon(resimYolu);
        
        resimEtiketi.setIcon(ikon);
    }
    
    private void sonucYaz(int puan,int saniye,String kazanmaDurumu){
        
        try{
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");
            LocalDateTime simdi = LocalDateTime.now();
            String zamanFormatli = dtf.format(simdi);
            
            FileWriter writer = new FileWriter(gameData, true);
            
            writer.write(String.valueOf(puan) + " " + String.valueOf(saniye) + " " + kazanmaDurumu + " " + zamanFormatli + "\n");
            writer.close();
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Oyununuzun sonucu kayıt alınırken bir hata oldu! " + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }
    
    private void eskiSkorlar(){
        try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setRowCount(0);
            
            if(!gameData.exists()){
                return;
            }
            
            BufferedReader reader = new BufferedReader(new FileReader(gameData));
            
            String satir;
            
            while((satir = reader.readLine()) != null){
                if(!satir.trim().isEmpty()){
                    String[] sutunVerileri = satir.split(" ");
                    
                    model.addRow(sutunVerileri);
                }
            }
            reader.close();
            
        }catch(IOException e){
            System.out.println("skorlar goruntulenirken sorun oluştu!" + e.getMessage());
        }
    }
    private void logGoster(){
        try{
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            
            model.setRowCount(0);
            
            if(!logData.exists()){
                return;
            }
            
            BufferedReader reader = new BufferedReader(new FileReader(logData));
            
            String satir;
            
            while((satir = reader.readLine()) != null){
                if(!satir.trim().isEmpty()){
                    String[] sutunVerileri = satir.split(" ");
                    
                    model.addRow(sutunVerileri);
                }
            }
            reader.close();
            
        }catch(IOException e){
            System.out.println("skorlar goruntulenirken sorun oluştu!" + e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel resimEtiketi;
    // End of variables declaration//GEN-END:variables
}
