/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adamasmaca;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahmut
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());
    String sifreler = "C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
    String log = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
    File logData = new File(log);
    File rgsData = new File(sifreler);  
    int girisDenemesi;
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        if(!rgsData.exists() || rgsData.length()==0){
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
        }else{
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
        }
        girisDenemesi = 3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Şifre:");

        jButton1.setText("Gir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Şifreyi belirle");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        textField1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sifre = textField1.getText();
        
        if(sifre.isEmpty()){
            
            logYaz("Şifre_alanı_boş.");
            
            JOptionPane.showMessageDialog(this, "Lütfen bir sifre giriniz.","Uyarı",JOptionPane.WARNING_MESSAGE);
            
            
        }else{
            try{
                BufferedReader reader = new BufferedReader(new FileReader(rgsData));
                
                String kayitliSifre = reader.readLine();
                reader.close();
                
                if(sifre.equals(kayitliSifre)){
                    
                    logYaz("giriş_yapıldı");
                    
                    JOptionPane.showMessageDialog(this, "Giriş başarılı! Oyun açılıyor...", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
                    
                    
                    
                    //Giriş yapıldıktan sonra GUI'a yönlendirilecek.
                    
                    new GUI().setVisible(true);
                    
                    this.dispose();
                }else{
                    logYaz("Yanlış_giriş_denemesi");
                    girisDenemesi--;
                    if(girisDenemesi > 0){
                        JOptionPane.showMessageDialog(this, "Yanlış bir sifre girdiniz."+ girisDenemesi +" Deneme hakkınız kaldı.","Uyarı",JOptionPane.WARNING_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "3 kez hatalı giriş yaptınız. Program kapatılıyor...","Hata",JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }
                
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Şifre kontrol edilirken bir hata oluştu!" + e.getMessage(), "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sifre = textField1.getText();
        if(sifre.isEmpty()){
            logYaz("Şifre_alanı_boş");
            JOptionPane.showMessageDialog(this, "Lütfen bir sifre giriniz.","Uyarı",JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                FileWriter writer = new FileWriter(rgsData);
                writer.write(sifre);
                writer.close();
                logYaz("Başarılı_şifre_kayıt.");
                
                
                
                //Giriş yapıldıktan sonra GUI'a gönderilecek.
                new GUI().setVisible(true);
                
                this.dispose();
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(this,"Şifre kaydedilirken bir hata oluştu!" + e.getMessage(),"Hata",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));

    }
    
    private void logYaz(String durumMesaji){
        
        try{
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");
            LocalDateTime simdi = LocalDateTime.now();
            String zamanFormatli = dtf.format(simdi);
            
            FileWriter writer = new FileWriter(logData, true);
            writer.write(durumMesaji + " " +zamanFormatli + "\n");
            writer.close();
            
            
            
        }catch(IOException e){
            System.out.println("Log dosyasına yazılamadı: " + e.getMessage());
        }
        
        
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
